osx_image: xcode8
language: objective-c
xcode_sdk: iphonesimulator10.0
git:
  depth: 1
cache:
- bundler
- cocoapods
before_install:
- xcrun instruments -w "iPhone 7 (10.0) [5F911B30-5F23-403B-9697-1DFDC24773C8]" ||
  echo "(Pre)Launched the simulator."
install:
- gem install bundler
- bundle install
- bundle exec pod keys set OauthKey $ELLO_CLIENT_KEY Ello
- bundle exec pod keys set OauthSecret $ELLO_CLIENT_SECRET Ello
- bundle exec pod keys set Domain $ELLO_DOMAIN Ello
- bundle exec pod keys set SodiumChloride $INVITE_FRIENDS_SALT Ello
- bundle exec pod keys set CrashlyticsKey $ELLO_CRASHLYTICS_KEY Ello
- bundle exec pod keys set HttpProtocol $ELLO_HTTP_PROTOCOL Ello
- bundle exec pod keys set SegmentKey $ELLO_SEGMENT_KEY Ello
- bundle exec pod keys set TeamId ABC123 Ello
- bundle exec pod repo update --silent
- bundle exec pod install
before_script:
- export LANG=en_US.UTF-8
script:
- gem install danger --no-ri --no-rdoc && danger
- set -o pipefail && xcodebuild -workspace Ello.xcworkspace -scheme Ello -configuration
  Debug -destination "OS=10.0,name=iPhone 7" clean test | xcpretty -f `xcpretty-travis-formatter`
notifications:
  slack:
    secure: ex5XcLhTVaN6bdA0iHsnaDGbifBD8AA5sQPKkFLDjMVy7MR1rrnvfWx8yqkFeJftX8DHPULb7Bpqsft5ydUWSVTb0002fraKqBni/apJkMceuFA6CP9R9jyVc0Yg7lQI/NiIcxkwOGlKXnezrShr3RB2XsjFEIz/hkCRMYCUqzA7zM/YBPUCKQDtEv2O+30UiGGx9l73mbIQKJbQ/2pAlqe+zFV4qy6+DT0mEbppnfcGtNbh4WhDADEsveTsYU7Akjwvip5U+hcq7WXa7KLMLm0HPBuRbVVR4NDBwSY+d1WBS89aFH2dYF2nQ4YyYZzLWqB6DpLPOCE91OvbfQ9AFhxc8QWL/MURrntzr4NnTaIPw0OBWfYBlzQ+8OlQdLLpAqkAuwT1ihmUSTgHuo7B5QbKJ750AXwIhUo3tMLZKbZ5f3LCCfKk8J8SKq8juagACgHwSVDm9mu30wHl+8uyNzc8p+8MXFx2/uUJ5oLZiVuLZpYtwunSRLFi2MTbCIcMbcMzhjwt865K8+qvJx9Bgw01BVqf5xCO8ue9OsE4PKZhDPTmrdezWbk5iVZKrdBzz/ivwXg+sJ5NeSREYcqE8fhidEg/3HkGkq1Fmw6/1128JIwM0AHbdegHJVzwwXUoes3gT8N1HwseiTNk8i8jibzf1lXzbe3k3xcBp58nnGI=
